### PR TITLE
Fix for mc 1.21.1

### LINKED ISSUE #16: IllegalArgumentException on server start-up
Paper 1.21.1-83
RedstoneProximitySensor 2.5.2

Paper changes some internals. On server start-up:
```
[22:23:52] [Server thread/INFO]: [RedstoneProximitySensor] Enabling RedstoneProximitySensor v2.5.2
[22:23:53] [Server thread/ERROR]: Error occurred while enabling RedstoneProximitySensor v2.5.2 (Is it up to date?)
java.lang.IllegalArgumentException: Can not set net.minecraft.world.item.component.ResolvableProfile field org.bukkit.craftbukkit.inventory.CraftMetaSkull.profile to com.mojang.authlib.GameProfile
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:228) ~[?:?]
        at java.base/jdk.internal.reflect.FieldAccessorImpl.throwSetIllegalArgumentException(FieldAccessorImpl.java:232) ~[?:?]
        at java.base/jdk.internal.reflect.MethodHandleObjectFieldAccessorImpl.set(MethodHandleObjectFieldAccessorImpl.java:115) ~[?:?]
        at java.base/java.lang.reflect.Field.set(Field.java:836) ~[?:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.mutateItemMeta(SkullCreator.java:298) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemWithBase64(SkullCreator.java:161) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.util.SkullCreator.itemFromBase64(SkullCreator.java:91) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.createMainMenu(IndividualMob.java:120) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.trigger.IndividualMob.<init>(IndividualMob.java:47) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.createMenu(PlayerListener.java:100) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.listener.PlayerListener.<init>(PlayerListener.java:49) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onEnable(RedstoneProximitySensor.java:70) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-82-1348e44] 
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
[22:23:53] [Server thread/INFO]: [RedstoneProximitySensor] Disabling RedstoneProximitySensor v2.5.2
[22:23:53] [Server thread/ERROR]: Error occurred while disabling RedstoneProximitySensor v2.5.2
java.lang.NullPointerException: Cannot read field "userSelectedInventory" because "this.playerListener" is null
        at RedstoneProximitySensor-2.5.2.jar/com.ugleh.redstoneproximitysensor.RedstoneProximitySensor.onDisable(RedstoneProximitySensor.java:132) ~[RedstoneProximitySensor-2.5.2.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:589) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:754) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:516) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1215) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[paper-1.21.1.jar:1.21.1-82-1348e44]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[?:?]
```

### PR DESCRIPTION
**Pull request by mastercake10**
Basically fixes #16. I updated the dependencies and repos to make it compile again, fixed a few enum values to fit to the newer MC versions and fixed the SkullCreator. 

I think it will not run on previous MC versions anymore tho. If thats desired, we need to compile it again against older mc versions and make the skull-thingy more flexible to only use the `ResolvableProfile` when its required as a parameter for setting the profile.

Tested on  `paper-1.21.1-98`.

### CODE REVIEW

**Comment by Ugleh** [comment]
Let me read the code changes in a bit and then I'll merge. Thanks for this as I wouldn't have done it. This whole project was meant to be archived by now.

**Comment by mastercake10** [comment]
Understandable. Someone messaged me if I could fix it, gave it a quick glance and saw that its not too hard to fix. Thought I'd create a PR to make others benefit from this.

**Comment by Ugleh** [comment]
@mastercake10 
Would you be about to build this and share the jar? I do not have anything setup on my computer for this, thanks.

**Comment by mastercake10** [comment]
sure, here you go (needed to zip it since github don't allow to upload .jars)

[RedstoneProximitySensor-2.zip](https://github.com/user-attachments/files/17120692/RedstoneProximitySensor-2.zip)

**Pull request merged**
